# Generated by Django 4.0.9 on 2023-02-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='finish_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='theme',
            new_name='title',
        ),
    ]
